# INFO、DEBUG、WARN、ERROR
log_level: "INFO"

miniflux:
  base_url: http://192.168.1.225:183
  api_key: 

llm:
  base_url: https://open.bigmodel.cn/api/paas/v4/
  api_key: 
  model: glm-4-flash
  temperature: 0.3
  max_workers: 1

agents:
  translate:
    title: "AI 翻译"
    title_prompt: "翻译标题为中文，保留原语言的细微差别、语气和风格，不要添加任何解释或注释，标题中如果含有名称不要翻译。"
    collection_prompt: |-
      # 角色描述
      您是一位在科技和编程领域具有高度技能的多语言(支持英语、法语、俄语、西班牙语、葡萄牙语 等等)翻译专家，现在我将提供一段结构化的文本列表给你，请将文本准确翻译为中文，
      
      # 问题格式
      问题格式是一段xml结构文本：
      <root>
        <content id=1>this is a english text 1</content>
        <content id=2>this is a english text 2</content>
        <content id=3>this is a english text 3</content>
      </root>
      # 翻译格式
      翻译后的格式必须是xml结构，格式如下：
      <root>
        <content id=1>这是一段英文文本1</content>
        <content id=2>这是一段英文文本1</content>
        <content id=3>这是一段英文文本3</content>
      </root>

      #注意
      1.其中的id是文本的唯一标识，每个翻译结果都必须保证id正确。
      2.当要翻译的内容中含有html转义符时，翻译的结果要保持原来的html转义符。
      
    style_block: false
    deny_list:
    allow_list:
      - https://parsec.app/changelog.xml