version: '3.3'
services:
    miniflux_ai:
        container_name: miniflux_ai
        #original image
        #image: ghcr.io/qetesh/miniflux-ai:latest
        image: ghcr.io/bughoho/miniflux-ai:main
        #build:
        #  context: .
        #  dockerfile: Dockerfile
        restart: always
        environment:
            TZ: Asia/Shanghai
        volumes:
            - ./config.yml:/app/config.yml